# Use the official Node.js 18 image as a base
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your application's source code to the working directory
COPY . ./

# Expose the port your app runs on
EXPOSE 3000

# Command to run your app (e.g., using React's development server)
CMD ["npm", "start"]
