FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

RUN echo "networksetup = 'host'" >> .npmrc

# Install dependencies
# Using a mirror or a different registry if npm has issues can be specified here
RUN npm install --verbose --registry=https://registry.npmjs.org/

# Copy the rest of your application's source code to the working directory
COPY . ./

# Expose the port your app runs on
EXPOSE 3000

# Command to run your app (e.g., using React's development server)
CMD ["npm", "start"]
